# Generated by Django 4.2.16 on 2024-09-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("calories", models.FloatField()),
                ("protein", models.FloatField()),
                ("carbs", models.FloatField()),
                ("fats", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("daily_calories", models.FloatField()),
                ("goal", models.CharField(max_length=50)),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
